### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by adalbertogc1** [pollination-apps/utci-heatmap#16]
Hello, 

I am trying to locally run this app in Python 3.10.7, I have created a virtual environment, and then installed all the dependencies in the `requirements.txt` as indicated in the `readme`  file, when I try to run the streamlit app I am getting this error:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/46672847/209094351-9da0fcf1-d8f1-42ca-ad2c-8ebd742409e6.png">

AttributeError: module 'numpy' has no attribute 'float'

I am having a similar issue in the any tutorial that uses `from ladybug.epw import EPW`
I  fixed this issue by running this line:
pip install --force-reinstall numpy<1.24
Maybe you should add this to the `requirements.txt` file.

**Comment by devangcx** [comment]
I wonder if you would face the same issue if you had used Python 3.7. We should probably start mentioning this but it is an implicit assumption for most of the apps that the user is running Python 3.7.

**Comment by ghost** [comment]
Hello @devngc  thank you for your response. I have downgraded the python version to 3.7 and I am facing other types of issues but may be due to my lack of experience with python, I will explore it a bit more and let you know.

**Comment by devangcx** [comment]
Can you share what those other types of issues are? I am using Python 3.7.9

**Comment by adalbertogc1** [comment]
Removed all my previous python installations and started one with Python 3.7.9 (64 bit). I can run the app now. I believe that the main error was that I wrongly installed the 32-bit version initially. 
Thank you for the responses.
